name: Build docs

on:
  workflow_call:

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install dependencies
        run: pdm sync -G :all
      - name: Run build
        run: pdm run docs-build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ${{ github.workspace }}/docs/_build
          retention-days: 1
          if-no-files-found: error
