name: Lint

on:
  workflow_call:

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up PDM
        id: pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install dependencies
        run: pdm sync -G :all
      - name: Cache pre-commit dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.pdm.outpus.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run lint
        run: pdm run _ci-lint-code
        env:
          FROM_REF: origin/${{ github.event.repository.default_branch }}
          TO_REF: HEAD

  lint-commits:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install dependencies
        run: pdm sync -G :all
      - name: Run lint-commits
        run: pdm run _ci-lint-commits
        env:
          FROM_REF: origin/${{ github.event.repository.default_branch }}
          TO_REF: HEAD

  passed:
    needs:
      - lint-code
      - lint-commits
    runs-on: ubuntu-latest
    steps:
      - name: Check lint code status
        if: ${{ needs.lint-code.result != 'success' }}
        run: exit 1
      - name: Check lint commits status
        if: ${{ needs.lint-commits.result != 'success' }}
        run: exit 1
