name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    if: github.event.base_ref == 'refs/heads/main'
    uses: ./.github/workflows/test.yaml
  build:
    needs: test
    uses: ./.github/workflows/build.yaml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist
      - name: Create Github Release
        id: github-release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
      - name: Publish to Pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
